version: 'version'

services:
  mongo:
    image: mongo
    ports:
      -27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: fred
      - MONGO_INITDB_ROOT_PASSWORD: fred

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME: fred
      - ME_CONFIG_MONGODB_ADMINPASSWORD: fred
      - ME_CONFIG_MONGODB_URL: mongodb://fred:fred@mongo:27017/
